[package]
authors = ["Zack Owens <zowens2009@gmail.com>"]
name = "paxos"
version = "0.1.0"

[dependencies]
log = "0.4"
rand = { version = "0.7", features = ["small_rng"] }
tokio = "0.1"
tokio-codec = "0.1"
futures = "0.1.17"
env_logger = "0.7"
tokio-timer = "0.2"
clap = "2.33.0"
either = "1.5.3"
tokio-io = "0.1.4"
serde_derive = "1.0.103"
serde_cbor = "0.11"
serde = "1.0.103"
bytes = "0.4"

[dev-dependencies]
assert_matches = "1.1.0"
